# SPDX-License-Identifier: GPL-2.0-only
#
# DKMS configuration for the CANLAB dual virtual-channel CSI-2 camera driver.

PACKAGE_NAME="canlab-rpi-dkms"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME="canlab"
BUILT_MODULE_LOCATION="build"
DEST_MODULE_LOCATION="/updates"

MAKE="make module KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"

POST_INSTALL="dkms.postinst"

AUTOINSTALL="yes"
